name: build_desktop
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK (Microsoft JDK 21)
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Install WiX Toolset on Windows for packaging MSI
      - name: Install WiX Toolset on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          ./gradlew unzipWix
          $env:PATH += "$(pwd)/build/wix311"
        shell: powershell

      # Build and package application for the current OS
      - name: Build for current OS with detailed logging
        run: |
          ./gradlew packageDistributionForCurrentOS --warning-mode all --info -p composeApp
        shell: bash

      # Upload the resulting build artifacts
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Desktop-${{ runner.os }}
          path: |
            composeApp/build/compose/binaries/main/msi/*
            composeApp/build/compose/binaries/main/deb/*

